apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-sensors
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: 17
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      memory: 512Mi
  source:
    git:
      # update when code is pushed to a new location
      url: $GITREPO
      ref:
        branch: main
